### ISSUE TITLE
DNS resolution failed while implementing API Server for Hyperledger Fabric Network using the AWS managed blockchain?

### ISSUE THREAD

**Issue by AldrinAJ** [aws-samples/non-profit-blockchain#96]
I have the Chiancode up and running over an EC2 instance. I would like to make my local machine as the API server. 

**Fabric Node side:**
I kept the EC2 instance acting as the fabric Node side. 

- It has a connection profile, package.json, app.js. I created two javascript files, which were used to register and enroll admin, and then user1. The certificates were stored inside a wallet folder of the app folder.

I was able to accomplish API calling by running the app.js file that contains API methods for the chaincode running over the EC2 instance. The connection profile is same as the connection profile mentioned in the aws-samples for ngo application.

The template:
```
Here is the connection.yaml file

name: "Test"
x-type: "hlfv1"
description: "My Network"
version: "1.0"

channels:
  mychannel:
    orderers:
      - orderer.com
    peers:
      peer1:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

organizations:
  Org1:
    mspid: %MEMBERID%
    peers:
      - peer1
    certificateAuthorities:
      - ca-org1

orderers:
  orderer.com:
    url: grpcs://%ORDERINGSERVICEENDPOINT%
    grpcOptions:
      ssl-target-name-override: %ORDERINGSERVICEENDPOINTNOPORT%
    tlsCACerts:
      path: %CAFILE%

peers:
  peer1:
    url: grpcs://%PEERSERVICEENDPOINT%
    eventUrl: grpcs://%PEEREVENTENDPOINT%
    grpcOptions:
      ssl-target-name-override: %PEERSERVICEENDPOINTNOPORT%
    tlsCACerts:
      path: %CAFILE%

certificateAuthorities:
  ca-org1:
    url: https://%CASERVICEENDPOINT%
    httpOptions:
      verify: false
    tlsCACerts:
      path: %CAFILE%
    registrar:
      - enrollId: %ADMINUSER%
        enrollSecret: %ADMINPWD%
    caName: %MEMBERID%
```

**Fabric API Server:** (local machine)
I am currently trying to call the API from my local machine by making it as the Fabric API server.
The things I did so far is as follows:
1) I have copied the package.json, connection.yaml, wallet/User1 to the local machine
2) I have modified the path or the certificates in the connection profile with respect to Fabric API server using

sed -i 's/localhost/[Fabric-Client-IP]/g' connection.yaml

3) Added entries in /etc/hosts such that they will point to Fabric Client. {I feel I might be wrong with this configurations}

```
127.0.0.1 localhost
[Fabric-Node side-IP] orderer.com
[Fabric-Node side-IP] peer1
```
Here is an example of how I gave the IP for peer1 and orderer.com in the entries.

> eg; 18.18.111.252 peer1
Once everything has been set up, I ran the app.js which ran at port 3000. While testing the api here using the local machine, I found few errors regarding DNS resolution.
```
{"error":{"message":"Unable to initialize channel. Attempted to contact 1 Peers. Last error was Error: 14 UNAVAILABLE: DNS resolution failed","stack":"Error: Unable to initialize channel. Attempted to contact 1 Peers. Last error was Error: 14 UNAVAILABLE: DNS resolution failed\n    at Network._initializeInternalChannel (/home/Desktop/app/node_modules/fabric-network/lib/network.js:119:12)\n    at <anonymous>"}}
```

I wonder where might be the issues over the configurations I attempted. Kindly advice. Thanks.
